In [1]:
import numpy as np 

## Creating Numpy Arrays from Python Lists

In [4]:
arr = np.array((1, 2, 3, 4))

In [5]:
[3.14, 4, 2, 3]

[3.14, 4, 2, 3]

In [7]:
arr = np.array((1, 2, 3, 4), dtype = 'float32')
print(arr)

[1. 2. 3. 4.]


In [8]:
arr.shape

(4,)

In [11]:
a2 = np.array([(1, 2, 3), (4, 5, 6)])
print(a2.shape)
print(a2.ndim)

(2, 3)
2


In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size

6

## Creating Numpy Arrays from Scratch

In [17]:
np.zeros([2, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.ones([2, 5], dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [25]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

### random

In [26]:
# Seed for reproducibility 
np.random.seed(0)

np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [27]:
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [28]:
np.random.randint(0, 10, (4, 5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])